# Generated by Django 5.0.1 on 2024-02-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dt_publicacao'],
            },
        ),
    ]
