# Generated by Django 5.0.2 on 2024-02-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('dt_publicacao', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('titulo', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-dt_publicacao'],
            },
        ),
    ]
