# Generated by Django 5.0.1 on 2024-02-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacao',
            old_name='imagem',
            new_name='thumnail',
        ),
    ]
