# Generated by Django 5.0.1 on 2024-02-21 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloBlog', '0003_rename_thumnail_publicacao_thumbnail'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dt_nascimento', models.DateField()),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='perfil/')),
            ],
        ),
    ]
