# Generated by Django 5.0.1 on 2024-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloBlog', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
