# Generated by Django 5.0.1 on 2024-02-22 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloBlog', '0005_alter_perfil_descricao_alter_perfil_foto'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('likes', models.IntegerField()),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='HelloBlog.publicacao')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
