# Generated by Django 5.0.1 on 2024-02-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloBlog', '0006_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nome',
            new_name='autor',
        ),
    ]
