# Generated by Django 5.0.1 on 2024-02-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloBlog', '0007_rename_nome_comentario_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='email',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
